name: flutter_application_1
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  file_picker: ^8.1.2
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  url_launcher: ^6.2.0
  uuid: ^4.4.0
  path_provider: ^2.1.0
  universal_html: ^2.2.0
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0
  share_plus: ^7.2.0
  flutter_pdfview: ^1.3.0
  flutter_local_notifications: ^17.2.1+1
  timezone: ^0.9.4  # Added for zonedSchedule 
  google_fonts: ^6.1.0
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700